-- 1. Create Table for TSLA Data
CREATE OR REPLACE TABLE TSLA_STOCK_DATA (
    DATE DATE,
    OPEN FLOAT,
    HIGH FLOAT,
    LOW FLOAT,
    CLOSE FLOAT,
    ADJ_CLOSE FLOAT,
    VOLUME NUMBER
);

-- 2. Create External Stage with Credentials
CREATE OR REPLACE STAGE MY_S3_STAGE
  URL = 's3://your-bucket-name/'
  CREDENTIALS = (
    AWS_KEY_ID = 'YOUR_ACCESS_KEY' 
    AWS_SECRET_KEY = 'YOUR_SECRET_KEY'
  );

-- 3. Load Data
COPY INTO TSLA_STOCK_DATA
FROM @MY_S3_STAGE/TSLA.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';