-- After Login to Snowflake, run the following commands in SnowSQL CLI

USE ROLE SNOW_PROJ_ADMIN_ROLE;
USE WAREHOUSE SNOW_LOADING_WH;
USE DATABASE SNOW_LOADING_PROJ_DB;
USE SCHEMA RAW_DATA_SCHEMA;

-- 1. Create File Format
CREATE OR REPLACE FILE FORMAT MY_PIPE_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = '|'
    SKIP_HEADER = 1;

-- 2. Create Internal Stage
CREATE OR REPLACE STAGE MY_INTERNAL_STAGE
    FILE_FORMAT = MY_PIPE_FORMAT;

-- 3. Upload File (Run this in CMD)
PUT file://<FILE PATH> @MY_INTERNAL_STAGE;

-- 4. Load Data into Table
COPY INTO CUSTOMER_DETAILS
FROM @MY_INTERNAL_STAGE
ON_ERROR = 'CONTINUE';